version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  web:
    image: elkozmon/zoonavigator-web:latest
    container_name: zoonavigator-web
    ports:
     - "8000:8000"
    environment:
      API_HOST: "api"
      API_PORT: 9000
    links:
     - api
    depends_on:
     - api
    restart: always
  api:
    image: elkozmon/zoonavigator-api:latest
    container_name: zoonavigator-api
    environment:
      SERVER_HTTP_PORT: 9000
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: ${ZK_HOSTNAME}:${ZK_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    image: mongo:3
  instance-management:
    image: sitewhere/service-instance-management:${SW_VERSION}
    environment:
      sitewhere.zookeeper.host: ${ZK_HOSTNAME}
  user-management:
    image: sitewhere/service-user-management:${SW_VERSION}
    environment:
      sitewhere.zookeeper.host: ${ZK_HOSTNAME}
  tenant-management:
    image: sitewhere/service-tenant-management:${SW_VERSION}
    environment:
      sitewhere.zookeeper.host: ${ZK_HOSTNAME}
  web-rest:
    image: sitewhere/service-web-rest:${SW_VERSION}
    ports:
     - "8080:8080"
    environment:
      sitewhere.zookeeper.host: ${ZK_HOSTNAME}
