version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_LOG4J_PROP: INFO
    volumes:
      - ${VOLUME_ROOT}/zookeeper:/opt/zookeeper-3.4.9/data

  zoonavigator-web:
    image: elkozmon/zoonavigator-web:latest
    ports:
     - "8000:8000"
    environment:
      API_HOST: "zoonavigator-api"
      API_PORT: 9000
    links:
     - zoonavigator-api
    depends_on:
     - zoonavigator-api
    restart: always

  zoonavigator-api:
    image: elkozmon/zoonavigator-api:latest
    environment:
      SERVER_HTTP_PORT: 9000
    restart: always

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG4J_LOGGER_KAFKA: INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_ROOT}/kafka:/kafka

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686" 
