version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks: 
      - sitewhere
    ports:
      - "2181:2181"
    environment:
      ZOO_LOG4J_PROP: INFO
    volumes:
      - ${VOLUME_ROOT}/zookeeper:/opt/zookeeper-3.4.9/data

  zoonavigator-web:
    image: elkozmon/zoonavigator-web:latest
    networks: 
      - sitewhere
    ports:
     - "8000:8000"
    environment:
      API_HOST: "zoonavigator-api"
      API_PORT: 9000
    links:
     - zoonavigator-api
    depends_on:
     - zoonavigator-api
    restart: always

  zoonavigator-api:
    image: elkozmon/zoonavigator-api:latest
    networks: 
      - sitewhere
    environment: 
      SERVER_HTTP_PORT: 9000

  kafka: 
    image: wurstmeister/kafka:1.0.0
    networks: 
      - sitewhere
    ports: 
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_BROKER_ID: sitewhere
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_ROOT}/kafka:/kafka
      
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    expose:
      - "9411"
      - "16686"
    networks: 
      - sitewhere
    ports: 
      - "9411:9411"
      - "16686:16686" 
      
networks: 
    sitewhere: 
        driver: overlay