version: '3.2'
services: 
  mongodb:
    image: mongo:3
    volumes:
      - ${VOLUME_ROOT}/mongodb:/data/db
      
  influxdb:
    image: influxdb:1.3-alpine
    ports:
      - "8086:8086"
    volumes:
      - ${VOLUME_ROOT}/influxdb:/var/lib/influxdb
      
  mosquitto:
    image: eclipse-mosquitto:1.4.12
    ports:
      - "1883:1883"
      
  instance-management:
    image: sitewhere/service-instance-management:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  user-management:
    image: sitewhere/service-user-management:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  tenant-management:
    image: sitewhere/service-tenant-management:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  device-management:
    image: sitewhere/service-device-management:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  event-management:
    image: sitewhere/service-event-management:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  event-search:
    image: sitewhere/service-event-search:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  asset-management:
    image: sitewhere/service-asset-management:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  event-sources:
    image: sitewhere/service-event-sources:${SW_VERSION}
    env_file:
      - sitewhere-instance.env
    environment:
      mqtt.host: mosquitto

  inbound-processing:
    image: sitewhere/service-inbound-processing:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  device-registration:
    image: sitewhere/service-device-registration:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  rule-processing:
    image: sitewhere/service-rule-processing:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  outbound-connectors:
    image: sitewhere/service-outbound-connectors:${SW_VERSION}
    env_file:
      - sitewhere-instance.env
    environment:
      mqtt.host: mosquitto

  batch-operations:
    image: sitewhere/service-batch-operations:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  schedule-management:
    image: sitewhere/service-schedule-management:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  command-delivery:
    image: sitewhere/service-command-delivery:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  presence-management:
    image: sitewhere/service-presence-management:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  streaming-media:
    image: sitewhere/service-streaming-media:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  label-generation:
    image: sitewhere/service-label-generation:${SW_VERSION}
    env_file:
      - sitewhere-instance.env

  web-rest:
    image: sitewhere/service-web-rest:${SW_VERSION}
    ports:
      - "8080:8080"
    env_file:
      - sitewhere-instance.env
      
networks:
  default:
    external:
      name: infrastructure_sitewhere
