apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sitewhere.fullname" . }}-jaeger
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.jaeger.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere.name" . }}-jaeger
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere.name" . }}-jaeger
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-jaeger
          image: "{{ .Values.image.registry }}/{{ .Values.jaeger.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.jaeger.service.ports.zipkin }}
              name: zipkin-port
              protocol: TCP
            - containerPort: {{ .Values.jaeger.service.ports.ui }}
              name: ui-port
              protocol: TCP
          env:       
            - name: "COLLECTOR_ZIPKIN_HTTP_PORT"
              value: "{{ .Values.jaeger.service.ports.zipkin }}"
