apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-kafka-svc
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - port: {{ .Values.kafka.service.inside.port }}
      targetPort: {{ .Values.kafka.service.inside.port }}
      protocol: TCP
      name: inside
    - port: {{ .Values.kafka.service.outside.port }}
      targetPort: {{ .Values.kafka.service.outside.port }}
      name: outside
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
