apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sitewhere.fullname" . }}-kafka
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere.name" . }}-kafka
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere.name" . }}-kafka
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-kafka
          image: "{{ .Values.image.registry }}/{{ .Values.kafka.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: inside
              containerPort: {{ .Values.kafka.service.inside.port }}
            - name: outside
              containerPort: {{ .Values.kafka.service.outside.port }}
          env:
            - name: "KAFKA_ADVERTISED_HOST_NAME"
              value: "{{ include "sitewhere.fullname" . }}-kafka-svc"
            - name: "KAFKA_BROKER_ID"
              value: "999"
            - name: "KAFKA_ZOOKEEPER_CONNECT"
              value: "{{ include "sitewhere.fullname" . }}-zookeeper-svc:{{ .Values.zookeeper.service.port }}"
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
              value: "{{ .Values.kafka.service.inside.port }}"
          volumeMounts:
            - name: {{ include "sitewhere.fullname" . }}-kafka-pv
              mountPath: /kafka
      volumes:
        - name: {{ include "sitewhere.fullname" . }}-kafka-pv
          persistentVolumeClaim:
            claimName: {{ include "sitewhere.fullname" . }}-kafka-pvc
