apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-user-management-svc
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.services.user_management.service.type }}
  ports:
    - port: {{ .Values.services.user_management.service.port }}
      targetPort: {{ .Values.services.user_management.service.port }}
      protocol: TCP
      name: grcp
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-user-management
    app.kubernetes.io/instance: {{ .Release.Name }}
