apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sitewhere.fullname" . }}-zookeeper
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere.name" . }}-zookeeper
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere.name" . }}-zookeeper
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-zookeeper
          image: "{{ .Values.image.registry }}/{{ .Values.zookeeper.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.zookeeper.service.port }}
              name: zookeeper
              protocol: TCP
          env:       
            - name: "ZOOKEEPER_LOG4J_PROP"
              value: "INFO"
          volumeMounts:
            - name: {{ include "sitewhere.fullname" . }}-zookeeper-pv
              mountPath: /opt/zookeeper-3.4.9/data
        - name: {{ .Chart.Name }}-zoonavigator
          image: "{{ .Values.image.registry }}/{{ .Values.zookeeper.zoonavigator.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:       
            - name: "API_HOST"
              value: "localhost"
            - name: "API_PORT"
              value: "9000"
          ports:
            - containerPort: {{ .Values.zookeeper.service.port }}
              name: zoonav-port
              protocol: TCP
        - name: {{ .Chart.Name }}-zoonavigator-api
          image: "{{ .Values.image.registry }}/{{ .Values.zookeeper.api.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:       
            - name: "SERVER_HTTP_PORT"
              value: "9000"
          ports:
            - containerPort: 9000
      volumes:
        - name: {{ include "sitewhere.fullname" . }}-zookeeper-pv
          persistentVolumeClaim:
            claimName: {{ include "sitewhere.fullname" . }}-zookeeper-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-zookeeper-svc
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: {{ .Values.zookeeper.service.port }}
      protocol: TCP
      name: zookeeper-port
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-zookeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitewhere.fullname" . }}-zoonav
  labels:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}
    helm.sh/chart: {{ include "sitewhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.zookeeper.zoonavigator.service.port }}
      targetPort: {{ .Values.zookeeper.zoonavigator.service.port }}
      portocol: TCP
      name: zoonav-port
  selector:
    app.kubernetes.io/name: {{ include "sitewhere.name" . }}-zookeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
